version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
      composer install &&
      until mysql -h db -u root -prootpass -e 'select 1'; do echo 'waiting for mysql'; sleep 1; done &&
      php artisan migrate:fresh --seed &&
      npm install &&
      npm run prod &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: phivedb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
